Replace github workflow release.yaml with an actual file

diff --git a/nautobot-app-private/{{ cookiecutter.project_slug }}/.github/workflows/release.yml b/nautobot-app-private/{{ cookiecutter.project_slug }}/.github/workflows/release.yml
--- a/nautobot-app-private/{{ cookiecutter.project_slug }}/.github/workflows/release.yml
+++ b/nautobot-app-private/{{ cookiecutter.project_slug }}/.github/workflows/release.yml
@@ -1,1 +1,154 @@
-../../../../nautobot-app/{{ cookiecutter.project_slug }}/.github/workflows/release.yml
+---
+name: "Release"
+on:  # yamllint disable-line rule:truthy rule:comments
+  release:
+    types: ["published"]
+
+env:
+  POETRY_VERSION: "2.1.3"
+  PYTHON_VERSION: "3.12"
+
+jobs:
+  build:
+    name: "Build package with poetry"
+    runs-on: "ubuntu-latest"
+    if: "startsWith(github.ref, 'refs/tags/v')"
+    steps:
+      - uses: "actions/checkout@v4"
+      - name: "Setup environment"
+        uses: "networktocode/gh-action-setup-poetry-environment@v7"
+        with:
+          poetry-version: "{% raw %}${{ env.POETRY_VERSION }}{% endraw %}"
+          python-version: "{% raw %}${{ env.PYTHON_VERSION }}{% endraw %}"
+          poetry-install-options: "--no-root"
+      - name: "Build Documentation"
+        run: "poetry run invoke build-and-check-docs"
+      - name: "Run Poetry Build"
+        run: "poetry build"
+
+      - name: "Check that the release tag matches the version in pyproject.toml"
+        run: |
+          if [ "{% raw %}${{ github.ref_name }}{% endraw %}" != "v$(poetry version -s)" ]; then exit 1; fi
+
+      - uses: "actions/upload-artifact@v4"
+        with:
+          name: "distfiles"
+          path: "dist/"
+          if-no-files-found: "error"
+
+  publish-artifactory:
+    name: "Push Package to JFrog Artifactory"
+    runs-on: "ubuntu-latest"
+    if: "startsWith(github.ref, 'refs/tags/v')"
+    needs: "build"
+    steps:
+      - uses: "actions/checkout@v4"
+      - name: "Setup environment"
+        uses: "networktocode/gh-action-setup-poetry-environment@v7"
+        with:
+          poetry-version: "{% raw %}${{ env.POETRY_VERSION }}{% endraw %}"
+          poetry-install-options: "--dry-run"
+
+      - name: "Retrieve built package from cache"
+        uses: "actions/download-artifact@v4"
+        with:
+          name: "distfiles"
+          path: "dist/"
+
+      - name: "Publish package distributions to JFrog Artifactory"
+        env:
+          POETRY_REPOSITORIES_ARTIFACTORY_URL: "{% raw %}${{ vars.ARTIFACTORY_URL }}{% endraw %}"
+          POETRY_HTTP_BASIC_ARTIFACTORY_USERNAME: "{% raw %}${{ secrets.ARTIFACTORY_USERNAME }}{% endraw %}"
+          POETRY_HTTP_BASIC_ARTIFACTORY_PASSWORD: "{% raw %}${{ secrets.ARTIFACTORY_PASSWORD }}{% endraw %}"
+        run: "poetry publish --repository artifactory --dist-dir dist"
+
+  slack-notify:
+    needs:
+      - "publish-artifactory"
+    runs-on: "ubuntu-latest"
+    env:
+      # Secrets cannot be directly referenced in if: conditionals. They must be set as a job env var first.
+      # Ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-using-secrets
+      SLACK_WEBHOOK_URL: "{% raw %}${{ secrets.OSS_PYPI_SLACK_WEBHOOK_URL }}{% endraw %}"
+      SLACK_WEBHOOK_TYPE: "INCOMING_WEBHOOK"
+      SLACK_MESSAGE: >-
+        *NOTIFICATION: NEW-RELEASE-PUBLISHED*\n
+        Repository: <{% raw %}${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}{% endraw %}>\n
+        Release: <{% raw %}${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}|${{ github.ref_name }}{% endraw %}>\n
+        Published by: <{% raw %}${{ github.server_url }}/${{ github.actor }}|${{ github.actor }}{% endraw %}>
+    steps:
+      - name: "Send a notification to Slack"
+        if: "{% raw %}${{ env.SLACK_WEBHOOK_URL != '' }}{% endraw %}"
+        uses: "slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3"  # v1.27.1
+        with:
+          payload: |
+            {
+              "text": "{% raw %}${{ env.SLACK_MESSAGE }}{% endraw %}",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "{% raw %}${{ env.SLACK_MESSAGE }}{% endraw %}"
+                  }
+                }
+              ]
+            }
+
+  create-pr-to-develop:
+    if: "github.event.release.target_commitish == 'main'"
+    permissions:
+      contents: "write"
+      pull-requests: "write"
+    name: "Create a PR from main into develop"
+    needs:
+      - "publish-artifactory"
+    runs-on: "ubuntu-latest"
+    steps:
+      - name: "Checkout main"
+        uses: "actions/checkout@v4"
+        with:
+          ref: "main"
+          fetch-depth: 0
+
+      - name: "Setup environment"
+        uses: "networktocode/gh-action-setup-poetry-environment@v7"
+        with:
+          poetry-version: "{% raw %}${{ env.POETRY_VERSION }}{% endraw %}"
+          poetry-install-options: "--no-root"
+
+      - name: "Create release branch from main"
+        id: "branch"
+        run: |
+
+          git config user.name "{% raw %}${{ github.actor }}{% endraw %}"
+          git config user.email "{% raw %}${{ github.actor }}{% endraw %}@users.noreply.github.com"
+
+          TAG_NAME="{% raw %}${{ github.event.release.tag_name }}{% endraw %}"
+          VERSION="${TAG_NAME#v}"
+
+          BRANCH_NAME="release-${VERSION}-to-develop"
+
+          # Ensure release branch doesn't already exist
+          if git rev-parse --verify origin/$BRANCH_NAME > /dev/null 2>&1; then
+            echo "Error: Release branch $BRANCH_NAME already exists."
+            exit 1
+          fi
+
+          git checkout -b "$BRANCH_NAME"
+
+          poetry version prepatch
+          git add pyproject.toml && git commit -m "Bump version"
+          git push origin "$BRANCH_NAME"
+
+          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
+
+      - name: "Create Pull Request to develop"
+        env:
+          GH_TOKEN: "{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}"
+        run: |
+          gh pr create \
+            --title "Post release {% raw %}${{ github.event.release.tag_name }}{% endraw %} to develop" \
+            --body "Please do a merge commit." \
+            --base "develop" \
+            --head "{% raw %}${{ steps.branch.outputs.branch_name }}{% endraw %}"
